### ISSUE TITLE
뉴스 타이틀

### ISSUE THREAD

**Issue by gzgr** [gzgr/semiconductor-news#1]
```yaml
version: "1"
post:
  - title: 뉴스 타이틀
  - description: 뉴스 설명
  - url: https://google.com
```
